name: Test

permissions:
  actions: write
  checks: write
  contents: write

on:
  # push:
  #   branches:
  #     - '*'
  repository_dispatch:
    types: [run_build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        git clone --recursive https://github.com/vitasdk/vita-toolchain
        cd vita-toolchain
        ./build.sh
        cd build
        sudo make install DESTDIR=${PWD}
    - name: print
      run: |
        mkdir toolchain-build
        cd vita-toolchain/build/usr/local
        cp -r "./" "../../../../toolchain-build"
    - name: print
      run: |
        sudo tar "cfvj" "toolchain-linux.tar.gz" "toolchain-build"
        sudo rm -r ./vita-toolchain
        sudo rm -r ./toolchain-build
    - name: abcdef
      run: |
        echo "ABDEF" >> log.txt
    - name: Commit files
      run: |
        git add .
        git commit -m "Merge" -a
        git pull --rebase
        git push origin master
