name: build-binutils

permissions:
  actions: write
  checks: write
  contents: write

on:
  # push:
  #   branches:
  #     - '*'
  repository_dispatch:
    types: [run_build]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y cmake cmake-data git build-essential autoconf automake libtool texinfo bison flex pkg-config
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        chmod +x *.sh
        mkdir _
        cd _
        cmake ../build_binutils/
        make -j$(nproc) tarball
        ls
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-binutils-linux
        path: ./_/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./_/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: binutils
        release_name: binutils
  build-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        chmod +x *.sh
        mkdir _
        cd _
        cmake ../build_binutils/
        make -j$(nproc) tarball
        ls
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-binutils-macos
        path: ./_/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./_/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: binutils
        release_name: binutils
  build-windows:
    # TODO match as build-linux
    # we don't know reason yet, mingw build was failed when libelf compille.
    # mingw output have to be static linking, and that this reason, we are able to use 22.04 in here
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y cmake cmake-data git build-essential autoconf automake libtool texinfo bison flex pkg-config g++-mingw-w64
    - name: build test
      run: |
        chmod +x *.sh
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        unset CXX
        unset CC
        mkdir _
        cd _
        cmake ../build_binutils/ -DCMAKE_TOOLCHAIN_FILE=../toolchain-x86_64-w64-mingw32.cmake
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-binutils-windows
        path: ./_/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./_/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: binutils
        release_name: binutils
