name: build-binutils

permissions:
  actions: write
  checks: write
  contents: write

on:
  # push:
  #   branches:
  #     - '*'
  repository_dispatch:
    types: [run_build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ls
