name: build-binutils

permissions:
  actions: write
  checks: write
  contents: write

on:
  # push:
  #   branches:
  #     - '*'
  repository_dispatch:
    types: [run_build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y cmake cmake-data git build-essential autoconf automake libtool texinfo bison flex pkg-config
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        chmod +x *.sh
        mkdir _
        cd _
        mkdir build
        cd build
        cmake ../../build_binutils/
        make -j$(nproc) tarball
        ls
    - name: after build
      run: |
        cp _/build/vitasdk-x86_64-linux-gnu-binutils-latest.tar.bz2 ./release/vitasdk-x86_64-linux-gnu-binutils-latest.tar.bz2
        sudo rm -r "./_"
    - name: Commit files
      run: |
        git add .
        git commit -m "Merge" -a
        git pull --rebase
        git push origin master
  build-macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        chmod +x *.sh
        mkdir _
        cd _
        mkdir build
        cd build
        cmake ../../build_binutils/
        make -j$(nproc) tarball
        ls
    - name: after build
      run: |
        cp _/build/vitasdk-x86_64-apple-darwin-binutils-latest.tar.bz2 ./release/vitasdk-x86_64-apple-darwin-binutils-latest.tar.bz2
        sudo rm -r "./_"
    - name: Commit files
      run: |
        git add .
        git commit -m "Merge" -a
        git pull --rebase
        git push origin master
  build-windows:
    # TODO match as build-linux
    # we don't know reason yet, mingw build was failed when libelf compille.
    # mingw output have to be static linking, and that this reason, we are able to use 22.04 in here
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo apt-get install -y cmake cmake-data git build-essential autoconf automake libtool texinfo bison flex pkg-config g++-mingw-w64
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: build test
      run: |
        chmod +x *.sh
        mkdir _
        cd _
        mkdir build
        cd build
        cmake ../../build_binutils/ -DCMAKE_TOOLCHAIN_FILE=../../toolchain-x86_64-w64-mingw32.cmake
        make -j$(nproc) tarball
        ls
    - name: after build
      run: |
        cp _/build/vitasdk-x86_64-mingw32-binutils-latest.tar.bz2 ./release/vitasdk-x86_64-mingw32-binutils-latest.tar.bz2
        sudo rm -r "./_"
    - name: Commit files
      run: |
        git add .
        git commit -m "Merge" -a
        git pull --rebase
        git push origin master
