name: Test

permissions:
  actions: write
  checks: write
  contents: write

on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
    - name: abcdef
      run: |
        echo "ABDEF" >> log.txt
    - name: git setting
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Commit files
      run: |
        git add .
        git commit -m "Merge" -a
        git pull --rebase
        git push origin master
    - name: build test
      run: |
        git clone --recursive https://github.com/vitasdk/vita-toolchain
        cd vita-toolchain
        ./build.sh
        cd build
        sudo make install DESTDIR=${PWD}
    - name: print
      run: |
        echo "${PATH}"
        tar -zcvf toolchain-linux.tar.gz ${PWD}/vita-toolchain/build/usr/local
        ls
